#!/usr/bin/env python

import argparse
import csv
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
import json
from math import ceil, floor, fmod, trunc
import os
import re
import subprocess
import sys
import traceback
from typing import Optional, Dict, List, Iterable
import requests

#-----------------------------------------------------------------------------------------------------------------------------
# Define constants
#-----------------------------------------------------------------------------------------------------------------------------

class Constants:

   # The BV-BRC URL
   BVBRC_URL = "https://www.bv-brc.org"

   # BV-BRC genome API endpoint
   GENOME_API = "https://www.bv-brc.org/api/genome/"

   # API record limit per request
   GENOME_API_LIMIT = 25000

   # Chunk size for IDs inside in(genome_id,(...)) to avoid huge URLs (414 errors)
   # (Even if limit is 25k, URLs can break before that.)
   GENOME_API_ID_CHUNK = 500

   # The default reference segment.
   DEFAULT_REF_SEGMENT = "HA"

   # The forester Java code parses the result .tre file and returns strain names and their annotations.
   FORESTER_JAR = "forester.jar"
   FORESTER_JAVA_PARAMETERS = "-Xmx8048m"
   FORESTER_PHYLOXML_CONVERTER_CLASS = "org.forester.application.phyloxml_converter"
   FORESTER_TREESORT_REFORMATE_CLASS = "org.forester.application.treesort_reformate"

   # The name of the descriptor file.
   DESCRIPTOR_FILE_NAME = "descriptor.csv"

   # The default name of the input FASTA file.
   INPUT_FASTA_FILE_NAME = "input.fasta"

   # The minimum number of genomes required for analysis.
   MIN_GENOMES = 10

   # The name of the subdirectory created in the working directory to hold intermediate files.
   OUTPUT_SUBDIRECTORY_NAME = "files"

   # The file extension of the PhyloXML file created from the annotated tree file.
   PHYLOXML_FILE_EXTENSION = ".xml"

   # A CSV file we will create and populate with reassortment data.
   REASSORTMENTS_FILE_NAME = "reassortments.csv"

   # The name of the result directories created by TreeSort will begin
   # with a segment name and end with this suffix.
   RESULT_DIRECTORY_SUFFIX = "-input.fasta.aln.treetime"

   # The result files created by TreeSort for every segment.
   RESULT_FILENAMES = [ "outliers.tsv", "root_to_tip_regression.pdf", "rtt.csv" ]

   # The names of the files we use to capture stdout and stderr.
   STDOUT_FILENAME = "stdout.txt"
   STDERR_FILENAME = "stderr.txt"

   # The name of the summary HTML file we will generate.
   SUMMARY_FILENAME = "index.html"

   # The name of the HTML template file used when generating the summary file.
   SUMMARY_TEMPLATE_FILENAME = "treesort_summary_template.html"

   # The file extension of the annotated tree file generated by TreeSort.
   TREE_FILE_EXTENSION = ".tre"

   # The text output files from TreeTime's stdout start with a segment name and end with this suffix.
   TREETIME_STDOUT_FILE_SUFFIX = "-treetime-stdout.txt"

   # A list of valid segments for the influenza virus.
   VALID_SEGMENTS = ["PB2", "PB1", "PA", "HA", "NP", "NA", "MP", "NS"]

   SEGMENT_NUM_TO_NAME = {
      "1": "PB2",
      "2": "PB1",
      "3": "PA",
      "4": "HA",
      "5": "NP",
      "6": "NA",
      "7": "MP",
      "8": "NS",
   }

# Custom ref attributes for a property element in the PhyloXML file.
class PHYLOXML_PROPERTY_REF:
   isReassorted = "ts:is_reassorted"
   isUncertain = "ts:is_uncertain"
   nodeID = "ts:node_id"
   ntDistance = "ts:nt_distance"
   segment = "ts:segment"

# Regular expressions used to parse the PhyloXML file generated by Forester.
class PHYLOXML_REGEX:
   BRANCH_LIST = re.compile(r"<branch_length>(?P<branch>[^(</branch_length>)]+)</branch_length")
   CLADE = re.compile(r'(?P<clade><clade>.*?)(?=(?:</?clade>)|$)', re.DOTALL)
   NAME = re.compile(r"<name>(?P<name>[^<]+)</name>")
   PROPERTY = re.compile(
      r'<property\s+ref="nh:comment"[^>]*>\s*(?P<value>.*?)\s*</property>',
      re.IGNORECASE | re.DOTALL
   )
   REASSORTED = re.compile(r",?is_reassorted=(?P<reassorted>[01])")
   SEGMENT_AND_DIST = re.compile(r"(rea=)?,?(?P<segment>\??[A-Za-z0-9]{1,3})\((?P<distance>\d+)\)", re.DOTALL)



#-----------------------------------------------------------------------------------------------------------------------------
# Enums
#-----------------------------------------------------------------------------------------------------------------------------

# The source of the input FASTA.
class InputSource(str, Enum):

   # FASTA pasted into a textarea on the UI.
   FastaData = "fasta_data"

   # Files generated by a previous run of prepare_treesort_dataset.sh
   FastaExistingDataset = "fasta_existing_dataset"

   # A workspace identifier for the FASTA file.
   FastaFileID = "fasta_file_id"

   # A workspace identifier for a genome group.
   FastaGroupID = "genome_group"
   

class MatchType(str, Enum):
   Default = "default"
   EPI = "epi"
   RegEx = "regex"
   Strain = "strain"


# Reassortment inference methods
class InferenceMethod(str, Enum):
   Local = "local"
   MinCut = "mincut"


# Command-line script flags / optional arguments.
class ScriptOption(str, Enum):
   CladesPath = "--clades"
   DescriptorPath = "-i"
   Deviation = "--dev"
   EqualRates = "--equal-rates"
   FastTree = "--fast"
   InferenceMethod = "-m"
   MatchOnEPI = "--match-on-epi"
   MatchOnRegex = "--match-on-regex"
   MatchOnStrain = "--match-on-strain"
   NoCollapse = "--no-collapse"
   OutputFilename = "-o"
   PValue = "--pvalue"
   Segments = "--segments"


# The reference segment inference method.
class TreeInference(str, Enum):
   FastTree = "FastTree"
   IQTree = "IQ-Tree"
   # RAxML = "RAxML" # Not implemented yet
 

#-----------------------------------------------------------------------------------------------------------------------------
# Utility functions
#-----------------------------------------------------------------------------------------------------------------------------

# Trim a string that's possibly null and always return a trimmed, non-null value.
def safe_trim(text: Optional[str]):
   if not text:
      return ""
   else:
      return text.strip()


#-----------------------------------------------------------------------------------------------------------------------------
# Classes
#-----------------------------------------------------------------------------------------------------------------------------

class GenomeMetadata:
   collection_date: str
   genome_id: str
   segments: list[str]
   strain: str
   subtype: str
   
   def __init__(self, collection_date: str, genome_id: str, segments: list[str], strain: str, subtype: str):

      self.genome_id = safe_trim(genome_id)
      if self.genome_id is None or len(self.genome_id) < 1:
         raise ValueError(f"Invalid genome ID in GenomeMetadata")

      collection_date = safe_trim(collection_date)
      if collection_date is None or len(collection_date) < 1:
         raise ValueError(f"Empty collection date in genome {self.genome_id}")
      
      self.collection_date = TreeSortRunner.normalize_collection_date(collection_date)
      if self.collection_date == "0000-00-00":
         raise ValueError(f"Invalid collection date \"0000-00-00\" in genome {self.genome_id}")

      self.strain = safe_trim(strain)
      if self.strain is None or len(self.strain) < 1:
         raise ValueError(f"Invalid strain for genome {self.genome_id}")
      
      self.subtype = safe_trim(subtype)
      if self.subtype is None or len(self.subtype) < 1:
         raise ValueError(f"Invalid subtype for genome {self.genome_id}")

      if segments is None or len(segments) < 1:
         raise ValueError(f"Invalid segments for genome {genome_id}")

      # Convert segment numbers to names.
      self.segments = TreeSortRunner.convert_segment_numbers_to_names(segments)


# The contents of the jobdesc.json file.
@dataclass
class JobData:
   clades_path: str
   deviation: float
   equal_rates: bool
   inference_method: Optional[InferenceMethod]
   input_fasta_existing_dataset: Optional[str]
   input_source: InputSource
   match_regex: Optional[str]
   match_type: Optional[MatchType]
   no_collapse: bool
   output_file: str
   output_path: str
   p_value: float
   ref_segment: str
   ref_tree_inference: TreeInference
   segments: Optional[str]
   input_fasta_data: Optional[str] = None
   input_fasta_file_id: Optional[str] = None
   input_fasta_group_id: Optional[str] = None

# A collection of result data to include in the analysis HTML file.
class Results:

   # This segment name maintains state when parsing over segment data in stdout.
   current_segment: str|None

   # JSON data that will be deserialized on the TreeSort analysis results page.
   json: str

   # The number of estimated reassortments found in the annotated tree file.
   reassortments: int

   # A list of text info for each segment.
   # TODO: Use an enum for the key?
   segment_data: dict[str, list[str]]

   # TreeSort's raw stdout and a list of parsed data.
   treesort_stdout: str
   treesort_list: list[str]

   # C-tor
   def __init__(self):
      self.current_segment = None
      self.json = ""
      self.reassortments = 0
      self.segment_data = {}
      self.treesort_stdout = ""
      self.treesort_list = []


# The class responsible for processing input parameters, preparing the input file, and 
# running the TreeSort application.
class TreeSortRunner:

   # The base URL
   base_url: str

   # the name of the directory containing the input FASTA file.
   input_directory: str

   # The name of the FASTA file to use as input. This is specified in job_data.
   input_filename: str

   # The JSON data for the job.
   job_data: JobData

   # Reassortment data generated in create_reassortments_csv_file.
   reassorted_strains = []

   # A collection of result data to include in the analysis HTML file.
   results: Results

   # Segments found in the input FASTA file.
   segments: List[str]
   
   # The directory where the scripts will be run.
   work_directory: str


   # C-tor
   def __init__(self, input_directory: str, job_data: JobData, work_directory: str):
         
      # The input directory
      self.input_directory = input_directory
      if not self.input_directory or len(self.input_directory) < 1:
         raise ValueError("The input directory parameter is invalid")
      
      # The work directory
      self.work_directory = work_directory
      if not self.work_directory or len(self.work_directory) < 1:
         raise ValueError("The work directory parameter is invalid")
      
      # Initialize member variables.
      self.segments = []

      # Determine the base URL.
      if "P3_BASE_URL" in os.environ:
         self.base_url = os.environ["P3_BASE_URL"]
      else:
         self.base_url = Constants.BVBRC_URL

      # Validate the job data.
      if not job_data:
         raise ValueError("A job data parameter was not provided")

      self.job_data = job_data

      # Trim the segment list string and make them uppercase.
      self.job_data.segments = safe_trim(self.job_data.segments).upper()

      # Validate the job data.
      if not TreeSortRunner.is_job_data_valid(self.job_data):
         raise ValueError("Job data in the constructor is invalid")

      # Populate the segments list from the segments string in the job data.
      segments = map(str.strip, (self.job_data.segments or "").split(","))
      if not bool(segments):
         raise ValueError("No valid segments were provided")
      self.segments = [segment for segment in segments if segment]

      # Initialize the results object.
      self.results = Results()


   def build_input_fasta_from_group(self, group_path: str, out_fasta_path: str) -> bool:
      """
      Building the input FASTA file from a genome group:
         1) Get genome IDs from the genome group
         2) Fetch metadata for each genome (chunked)
         3) Download FASTA for each genome
         4) Rewrite FASTA headers and validate the FASTA content
         5) Write the FASTA file to out_fasta_path
      """
      sys.stdout.write(f"\nBuilding input FASTA from genome group: {group_path}\n")

      genome_ids = self.get_genome_ids_from_group(group_path)
      if genome_ids is None or len(genome_ids) < 1:
         return False
      sys.stdout.write(f"Genome IDs found in group: {len(genome_ids)}\n")

      meta = self.fetch_all_metadata(genome_ids)
      sys.stdout.write(f"Metadata records fetched: {len(meta)}\n")

      valid_genomes = 0

      # Create and write sequences to the FASTA file.
      with open(out_fasta_path, "w", encoding="utf-8") as fout:
         for genome_id in genome_ids:

            # DEBUG
            sys.stdout.write(f"Genome {genome_id}\n")

            try:
               # Get the genome metadata for this genome ID.
               genome = meta.get(genome_id)
               if not genome:
                  sys.stdout.write(f"SKIP_MISSING_METADATA genome_id={genome_id}\n")
                  continue

               fasta = self.download_genome_fasta(genome_id)
               if not fasta or len(safe_trim(fasta)) == 0:
                  sys.stdout.write(f"SKIP_EMPTY_FASTA genome_id={genome_id}\n")
                  continue

               # Reformat the FASTA headers and validate the sequences.
               new_fasta = self.process_genome_fasta(fasta, genome)

               if len(new_fasta) > 0:

                  # Write the FASTA to the file.
                  fout.write(new_fasta)

                  valid_genomes += 1

            except Exception as e:
               sys.stderr.write(f"Error in genome {genome_id}:\n {str(e)}")

      if valid_genomes < Constants.MIN_GENOMES:
         sys.stderr.write(f"At least {Constants.MIN_GENOMES} genomes are required for analysis but only {valid_genomes} were provided")
         return False
      
      sys.stdout.write(f"The input FASTA file was created from the genome group ({out_fasta_path})\n")
      return True

   def _chunked(self, items: List[str], n: int) -> Iterable[List[str]]:
      for i in range(0, len(items), n):
         yield items[i:i+n]


   @staticmethod
   def convert_segment_numbers_to_names(segment_numbers: list[str]):
      """ Convert a list of numeric segments to segment names. """
      segment_names = []
      
      for segment_number in segment_numbers:
         segment_number = safe_trim(segment_number)
         if len(segment_number) < 1:
            continue

         # Convert numeric segment to canonical name
         segment_name = Constants.SEGMENT_NUM_TO_NAME.get(segment_number, "")
         if len(segment_name) > 0:
            segment_names.append(segment_name)

      return segment_names


   # Parse the annotated tree file for reassorted strains and create "reassortments.csv".
   def create_reassortments_csv_file(self) -> bool:

      sys.stdout.write("\nIn TreeSortRunner.create_reassortments_csv_file\n")
      
      # The result status defaults to true.
      result_status = True

      # Initialize the list of results.
      results = []

      # The paths of the CSV output file and the annotated tree input file.
      csv_file_path = f"{self.work_directory}/{self.job_data.output_file}.csv"
      tree_file_path = f"{self.work_directory}/{self.job_data.output_file}{Constants.TREE_FILE_EXTENSION}"

      # The path of the strain reassortments CSV file we will create.
      reassortments_path = f"{self.work_directory}/{Constants.REASSORTMENTS_FILE_NAME}"

      # Get the path for forester.jar.
      # TODO: this is only temporary...forester.jar will be updated in the container soon (?).
      top = safe_trim(os.getenv("KB_TOP"))
      if len(top) < 1:
         raise Exception("Invalid KB_TOP environment variable in create_reassortments_csv_file.")
   
      # The path depends on whether TreeSort is run in production or development.
      dev_path = os.path.join(top, "modules", "treesort", "lib", Constants.FORESTER_JAR)
      prod_path = os.path.join(top, "lib", Constants.FORESTER_JAR)

      if os.path.exists(prod_path):
         forester_path = prod_path
      elif os.path.exists(dev_path):
         forester_path = dev_path
      else:
         raise Exception(f"Unable to find {Constants.FORESTER_JAR}")

      try:
         cmd = ["java", Constants.FORESTER_JAVA_PARAMETERS, "-cp", forester_path, Constants.FORESTER_TREESORT_REFORMATE_CLASS]

         # Add the path of the annotated tree file.
         cmd.append(tree_file_path)

         # Add the path of the CSV output file.
         cmd.append(csv_file_path)

         # Display the command about to be run.
         print(f"{' '.join(cmd)}\n")

         # Run the command
         cmd_result = subprocess.run(cmd, shell=False, check=True)

         if cmd_result.returncode > 0 or not os.path.exists(csv_file_path):
            raise Exception(f"Forester was unable to generate the CSV file")
         
         # Open the CSV file
         with open(csv_file_path, newline="", encoding="utf-8") as csvfile:
            reader = csv.reader(csvfile)

            sys.stdout.write("\nReading the results CSV file.\n")

            for row in reader:
               
               is_reassorted = False
               is_uncertain = False

               # Get the strain/isolate name.
               strain = safe_trim(row[0])
               if len(strain) < 1:
                  continue
               
               # Maintain a distance value for each segment.
               PB2 = ""
               PB1 = ""
               PA = ""
               HA = ""
               NP = ""
               NA = ""
               MP = ""
               NS = ""

               reassortment = ""

               # Look for annotations in columns 1 and 2 (column 0 should have the strain name).
               annotation1 = row[1] if len(row) > 1 else None
               annotation2 = row[2] if len(row) > 2 else None

               # Did this strain have reassortment?
               if annotation1 == "is_reassorted=1":
                  # This column should have one or more segment names and distances.
                  if not annotation2:
                     continue
                  reassortment = annotation2
                  is_reassorted = True

               elif annotation2 == "is_reassorted=1":
                  # This column should have one or more segment names and distances.
                  if not annotation1:
                     continue
                  reassortment = annotation1
                  is_reassorted = True

               # If reassortment was detected we will determine the affected segment(s).
               if is_reassorted:

                  # &rea="NA(124)"
                  
                  # Update the reassortments count in the results.
                  self.results.reassortments += 1

                  # Determine which segments were reassorted and get each one's distance.
                  for token in reassortment.replace("rea=", "").strip().split(","):

                     if token.startswith("?"):
                        is_uncertain = True
                        token = token[1:]

                     match = re.match(r"([A-Z0-9]+)\((\d+)\)", token)
                     if match:
                        name, number = match.groups()
                        if name == "PB2":
                           PB2 = number
                        elif name == "PB1":
                           PB1 = number
                        elif name == "PA":
                           PA = number
                        elif name == "HA":
                           HA = number
                        elif name == "NP":
                           NP = number
                        elif name == "NA":
                           NA = number
                        elif name == "MP":
                           MP = number
                        elif name == "NS":
                           NS = number
                  
               # Update the results
               results.append({
                  "strain": strain, 
                  "is_reassorted": "Y" if is_reassorted else "",
                  "is_uncertain": "Y" if is_uncertain else "",
                  "PB2": PB2,
                  "PB1": PB1,
                  "PA": PA,
                  "HA": HA,
                  "NP": NP,
                  "NA": NA,
                  "MP": MP,
                  "NS": NS,
               })

         if len(results) > 0:

            sys.stdout.write(f"Writing transformed reassortment data to {reassortments_path}\n\n")

            # Sort the results so that the reassorted strains are at the top.
            sorted_results = sorted(results, key=lambda r: r["is_reassorted"], reverse=True)

            # Create the strain reassortments file.
            with open(reassortments_path, "w+", newline="", encoding="utf-8") as result_file:
               writer = csv.DictWriter(result_file, fieldnames=["strain", "is_reassorted", "is_uncertain", "PB2", "PB1", "PA", "HA", "NP", "NA", "MP", "NS"])
               writer.writeheader()
               writer.writerows(sorted_results)

         else:
            sys.stderr.write("No strains were found in the CSV results file")

         # TODO: Delete the CSV file created by forester.jar?

         # Add the reassortments count to the list of TreeSort messages in the results object.
         s = "" if self.results.reassortments == 1 else "s"
         self.results.treesort_list.append(f"TreeSort found {self.results.reassortments} reassortment event{s}")
         
      except Exception as e:
         sys.stderr.write(f"Error in TreeSort:\n {e}\n")
         return False
 
      return result_status
   

   # Create the summary report file.
   def create_summary_html(self) -> bool:

      # The top-level path 
      top = safe_trim(os.getenv("KB_TOP"))
      if len(top) < 1:
         raise Exception("Invalid KB_TOP environment variable in create_summary_html.")
      
      # The path depends on whether TreeSort is run in production or development.
      dev_path = os.path.join(top, "modules", "treesort", "lib", Constants.SUMMARY_TEMPLATE_FILENAME)
      prod_path = os.path.join(top, "lib", Constants.SUMMARY_TEMPLATE_FILENAME)

      if os.path.exists(prod_path):
         template_path = prod_path
      elif os.path.exists(dev_path):
         template_path = dev_path
      else:
         raise Exception(f"Unable to find {Constants.SUMMARY_TEMPLATE_FILENAME}")

      # The HTML template file as a string.
      html_template = None

      try:
         with open(template_path, "r", encoding="utf-8") as file:
            html_template = safe_trim(file.read())
            if len(html_template) < 1:
               raise Exception("Invalid HTML template")
            
      except FileNotFoundError:
         raise Exception(f"Error: The file {template_path} was not found.")
      
      except Exception as e:
         raise Exception(f"An error occurred: {e}")

      # Format the stdout from prepare_treesort_dataset and TreeSort as HTML.
      self.format_results()


      treesort_summary = ""

      if len(self.results.treesort_list) > 0:

         for item in self.results.treesort_list:
            treesort_summary += f"<li>{item}</li>"

         treesort_summary = f"<ul>{treesort_summary}</ul>"

      # The values of the JavaScript variables in the template.
      js_variables = {
         "{{nexus_filename}}": f"{self.job_data.output_file}{Constants.TREE_FILE_EXTENSION}",
         "{{output_subdirectory}}": Constants.OUTPUT_SUBDIRECTORY_NAME, 
         "{{phyloxml_filename}}": f"{self.job_data.output_file}{Constants.PHYLOXML_FILE_EXTENSION}",
         "{{reassortments_filename}}": Constants.REASSORTMENTS_FILE_NAME, 
         "\"{{results_json}}\"": self.results.json,
         "{{segments}}": self.job_data.segments,
         "{{treesort_summary}}": treesort_summary,
         "{{workspace_folder}}": f"{self.job_data.output_path}/.{self.job_data.output_file}/",
      }

      # Replace all JavaScript variable strings in the template text.
      for key, value in js_variables.items():
         html_template = html_template.replace(key, value)

      # The summary file will be created in the work directory.
      summary_path = f"{self.work_directory}/{Constants.SUMMARY_FILENAME}"

      try:
         # Create the summary HTML file.
         with open(summary_path, "w+") as summary_file:
            summary_file.write(str(html_template))

      except Exception as e:
         raise IOError(f"Error creating the summary file:\n {e}\n")

      return True


   # Delete intermediate files that are not needed in the output.
   def delete_unnecessary_files(self) -> bool:

      files = [
         Constants.DESCRIPTOR_FILE_NAME, 
         f"{self.job_data.output_file}.csv"
      ]

      for file in files:
         file_path = f"{self.work_directory}/{file}"
         if os.path.exists(file_path):
            try:
               subprocess.run(["rm", file_path], shell=False, check=True)
            except Exception as e:
               sys.stderr.write(f"Unable to delete file {file_path}:\n {e}\n")

      return True
   

   def download_genome_fasta(self, genome_id: str) -> str|None:
      """
      Uses p3-genome-fasta <genome_id> to return FASTA for the specified genome.
      """
      result = None

      try:
         result = subprocess.run(
            ["p3-genome-fasta", genome_id],
            shell=False,
            capture_output=True,
            check=True,
            text=True
         )

         if result is None:
            raise Exception(f"Invalid result when downloading FASTA for genome {genome_id}\n")
         if result.returncode != 0:
            raise Exception(result.stderr)
         
      except subprocess.CalledProcessError as cpe:  
         sys.stderr.write(f"Error downloading FASTA for genome {genome_id}:\n {cpe.stderr}\n")
         return None
      except Exception as e:
         sys.stderr.write(f"Error downloading FASTA for genome {genome_id}:\n {str(e)}\n")

      if result is None:
         return None
      
      return result.stdout

   
   # Create a PhyloXML version of the result tree.
   def export_tree_as_phyloxml(self) -> bool:

      sys.stdout.write("\nIn TreeSortRunner.export_tree_as_phyloxml\n")
      
      # The result status defaults to true.
      result_status = True

      # The paths of the annotated tree file and the PhyloXML file that will be created.
      tree_file_path = f"{self.work_directory}/{self.job_data.output_file}{Constants.TREE_FILE_EXTENSION}"
      phyloxml_file_path = f"{self.work_directory}/{self.job_data.output_file}{Constants.PHYLOXML_FILE_EXTENSION}"
      
      # Get the path for forester.jar.
      # TODO: this is only temporary...forester.jar will be updated in the container soon (?).
      top = safe_trim(os.getenv("KB_TOP"))
      if len(top) < 1:
         raise Exception("Invalid KB_TOP environment variable in export_tree_as_phyloxml.")
   
      # The path depends on whether TreeSort is run in production or development.
      dev_path = os.path.join(top, "modules", "treesort", "lib", Constants.FORESTER_JAR)
      prod_path = os.path.join(top, "lib", Constants.FORESTER_JAR)

      if os.path.exists(prod_path):
         forester_path = prod_path
      elif os.path.exists(dev_path):
         forester_path = dev_path
      else:
         raise Exception(f"Unable to find {Constants.FORESTER_JAR}")

      # Use Forester to export the Nexus file as a PhyloXML file.
      try:
         cmd = ["java", Constants.FORESTER_JAVA_PARAMETERS, "-cp", forester_path, 
            Constants.FORESTER_PHYLOXML_CONVERTER_CLASS,
            "-f=nn",
            tree_file_path,
            phyloxml_file_path]

         # Display the command about to be run.
         print(f"{' '.join(cmd)}\n")

         # Run the command
         cmd_result = subprocess.run(cmd, shell=False, check=True, capture_output=True)

         if cmd_result.returncode > 0 or not os.path.exists(phyloxml_file_path):
            raise Exception(f"Forester was unable to export the PhyloXML file")

      except subprocess.CalledProcessError as cpe:  
         sys.stderr.write(f"Error exporting tree as PhyloXML:\n {cpe.stderr}\n")
         return False 
      except Exception as e:
         sys.stderr.write(f"Error exporting tree as PhyloXML:\n {e}\n")
         return False
 

      # Reformat the comment property in the PhyloXML generated by Forester as one or more properties.
      try:
         # Open the PhyloXML file.
         with open(phyloxml_file_path, "r", encoding="utf-8") as output_file:
            phylo_xml = output_file.read()

         # Process all matching clade elements in the PhyloXML.
         phylo_xml = PHYLOXML_REGEX.CLADE.sub(self.process_phyloxml_clade, phylo_xml)

         # Write the modified content back to the file
         with open(phyloxml_file_path, 'w', encoding='utf-8') as file:
            file.write(phylo_xml)

      except Exception as e:
         sys.stderr.write(f"Error in export_tree_as_phyloxml:\n {e}\n")
         return False
 
      return result_status


   def fetch_all_metadata(self, genome_ids: List[str]) -> Dict[str, GenomeMetadata]:
      """
      Fetch in chunks to avoid enormous URL length (even if API limit is 25k).
      """
      all_genomes: Dict[str, GenomeMetadata] = {}

      try:
         for batch in self._chunked(genome_ids, Constants.GENOME_API_ID_CHUNK):
            batch_genomes = self.fetch_metadata_for_ids(batch)
            all_genomes.update(batch_genomes)
      except Exception as e:
         sys.stderr.write(f"Error fetching metadata for {len(genome_ids)} genome IDs:\n {e}\n")
         return all_genomes

      sys.stdout.write(f"Fetched metadata for {len(genome_ids)} genome(s)\n")

      if len(all_genomes) < Constants.MIN_GENOMES:
         raise Exception(f"At least {Constants.MIN_GENOMES} genomes are required for analysis and only {len(all_genomes)} valid genomes were included")
               
      return all_genomes


   def fetch_metadata_for_ids(self, genome_ids: List[str]) -> Dict[str, GenomeMetadata]:
      """
      Calls:
        /api/genome/?in(genome_id,(...))&select(genome_id,strain,subtype,segment,collection_date)&limit(25000)
      Returns dict[genome_id] = {strain, subtype, segment, collection_date}
      """
      ids_csv = ",".join(genome_ids)

      url = (
         f"{Constants.GENOME_API}"
         f"?in(genome_id,({ids_csv}))"
         f"&select(genome_id,strain,subtype,segment,collection_date)"
         f"&limit({Constants.GENOME_API_LIMIT})"
      )

      genomes: Dict[str, GenomeMetadata] = {}

      try:
         r = requests.get(url, timeout=60)
         r.raise_for_status()

         # Example JSON: [{"collection_date":"2011-03-21","strain":"D/swine/Oklahoma/1334/2011","segment":["1","2","3","4","5","6","7"],"genome_id":"1173138.25"}]
         data = r.json()

         # Iterate over all genome metadata in the JSON.
         for rec in data:
            try:
               genome = GenomeMetadata(
                  collection_date=rec.get("collection_date"),
                  genome_id = str(rec.get("genome_id", "")),
                  segments = rec.get("segment"),
                  strain = rec.get("strain"),
                  subtype = rec.get("subtype")
               )

               # Validate the genome metadata.
               if not self.is_genome_metadata_valid(genome):
                  continue

               # Add the genome metadata to the dictionary that will be returned.
               genomes[genome.genome_id] = genome

            except Exception as e:
               sys.stderr.write(str(e))
               continue
            
            """
            # dmd 09/16/26 Segment is a list of segment numbers.
            segment_numbers = rec.get("segment")
            if isinstance(segment_numbers, str):
               # This will probably never be reached, but just in case...
               segment_numbers = [segment_numbers]

            # The segment numbers will be converted to names and added to this comma-delimited string.
            segment_names = ""
            
            for segment_number in segment_numbers:
               segment_number = safe_trim(segment_number)
               if len(segment_number) < 1:
                  continue

               # Convert numeric segment to canonical name
               segment_name = Constants.SEGMENT_NUM_TO_NAME.get(segment_number, "")
               if len(segment_name) > 0:
                  # Preface with a comma if the delimited list isn't empty.
                  if len(segment_names) > 0:
                     segment_names += ","
                  segment_names += segment_name

            meta[gid] = {
               "strain": safe_trim(rec.get("strain")),
               "subtype": safe_trim(rec.get("subtype")),
               "segment": segment_names,
               "collection_date": self.normalize_collection_date(rec.get("collection_date")),
            }"""

         sys.stdout.write(f"Fetched metadata for {len(genome_ids)} genomes\n")

      except Exception as e:
         sys.stderr.write(f"An error occurred fetching genome metadata:\n {e}\n")

      return genomes


   # Format a datetime for the start and end times of program execution.
   @staticmethod
   def format_datetime(dt: datetime) -> str:

      # Portable 12-hour time, lowercase am/pm, and mm/dd/yy date
      return dt.strftime("%I:%M%p, %m/%d/%y").lstrip("0").replace("AM", "am").replace("PM", "pm")
   

   # Format the end datetime and include the duration between it and the start datetime.
   @staticmethod
   def format_end_datetime_with_duration(end: datetime, start: datetime) -> str:

      formatted_end = TreeSortRunner.format_datetime(end)

      total_seconds = int((end - start).total_seconds())
      minutes, seconds = divmod(total_seconds, 60)
      parts = []

      if minutes:
         parts.append(f"{minutes} minute{'s' if minutes != 1 else ''}")

      parts.append(f"{seconds} second{'s' if seconds != 1 else ''}")

      return f"{formatted_end} ({', '.join(parts)})" 
 

   # Format the Results object's data as HTML.
   # TODO: That's not what this is doing. What is its purpose?!?
   def format_results(self):

      if not self.results:
         raise Exception("The results object is invalid")
      
      # Parse TreeSort's stdout
      stdout = safe_trim(self.results.treesort_stdout)
      if len(stdout) > 0:
         
         # Iterate over every line from stdout and parse it.
         for line in stdout.splitlines():
            self.parse_treesort_stdout_line(line)

      # Parse the segment-specific output files containing TreeTime's stdout.
      self.process_treetime_stdout_files()

      # Generate JSON for segment_data in the results object.
      segments = {}

      # Generate JSON for the segment data.
      for segment in self.results.segment_data.keys():

         # JSON for this segment's data.
         segments[segment] = self.results.segment_data[segment]

      results_json = {
         "segments": segments,
         "summary": self.results.treesort_list
      }

      self.results.json = json.dumps(results_json)
      sys.stdout.write(f"\n\n{self.results.json}\n\n")

      
   # Convert the root date formatted as a decimal to a standard MM/DD/YYYY.
   def format_root_date(self, str_decimal: str, year: str):

      """ 
      Here's how TreeSort converts a date into a decimal format:
      
      decimal_date = ((date.month - 1) * 30 + date.day) / 365.0  + date.year
      
      """

      result_date = "invalid"

      if not str_decimal or len(str_decimal) < 1 or not year or len(year) < 1:
         return result_date

      f_decimal = floor((float(str_decimal) * 365.0)+ 0.5)
      
      try:
         # Divide by 365 and "round half up".
         f_decimal = floor((float(str_decimal) * 365.0) + 0.5)
      
         # Calculate the month and make sure it has 2 digits.
         month = str(trunc(f_decimal / 30) + 1)
         if len(month) == 1:
            month = f"0{month}"

         # Calculate the day and make sure it has 2 digits.
         day = str(ceil(fmod(f_decimal, 30)))
         if len(day) == 1:
            day = f"0{day}"

         result_date = f"{month}/{day}/{year}"

      except Exception as e:
         sys.stderr.write(f"Unable to format a date in decimal format:\n {e}\n")
         result_date = "invalid"
      
      return result_date
   

   def get_genome_ids_from_group(self, group_path: str) -> List[str]|None:
      """
      Uses p3-get-genome-group "<workspace path>" and extracts genome_ids like 11320.471792
      """
      try:
         result = subprocess.run(
            ["p3-get-genome-group", group_path],
            shell=False,
            capture_output=True,
            check=True,
            text=True
         )
         if result.returncode != 0:
            raise Exception(result.stderr)

         ids: List[str] = []
         for line in result.stdout.splitlines():
            line = safe_trim(line)
            if re.fullmatch(r"\d+\.\d+", line):
               ids.append(line)

         if not ids:
            raise ValueError(f"No genome IDs found in genome group: {group_path}")

         return ids

      except subprocess.CalledProcessError as cpe:  
         sys.stderr.write(f"Error reading genome group:\n {cpe.stderr}\n")
         return None
      except Exception as e:
         sys.stderr.write(f"Error reading genome group:\n {e}")
         return None


   def is_genome_metadata_valid(self, genome: GenomeMetadata) -> bool:
      """ Evaluate the segment information in the genome metadta. """
      if genome is None:
         sys.stderr.write("Invalid genome")
         return False

      # Does the genome have the reference segment?
      if not self.job_data.ref_segment in genome.segments:
         sys.stderr.write(f"Genome {genome.genome_id} doesn't have the reference segment {self.job_data.ref_segment}")
         return False

      valid_segments = 0

      # Does it have at least one of the requested segments (other than the ref segment)?
      for segment in genome.segments:
         if segment in self.segments:
            valid_segments += 1

      if valid_segments < 2:
         sys.stderr.write(f"Genome {genome.genome_id} doesn't have enough segments for analysis")
         return False

      return True
   

   # Is the JobData instance valid?
   @staticmethod
   def is_job_data_valid(job_data: JobData) -> bool:

      sys.stdout.write("\nIn TreeSortRunner.is_job_data_valid\n")

      try:
         if not job_data or not isinstance(job_data, JobData):
            raise Exception("job_data is empty")
         
         # Inference method
         if job_data.inference_method not in [m.value for m in InferenceMethod]:
            job_data.inference_method = InferenceMethod.Local

         # Validate the job's input_source.
         TreeSortRunner.validate_input_source(job_data) 

         # Match type and match regex
         match_regex = safe_trim(job_data.match_regex)
         if job_data.match_type == MatchType.RegEx and len(match_regex) < 1:
            raise ValueError("The match regular expression was not provided")

         # Validate the output path.
         if not job_data.output_path:
            raise ValueError("The output path is invalid")

         # Validate the output filename
         if not job_data.output_file:
            raise ValueError("The output filename is invalid")
         
         # If output_file has a file extension, remove it (it will be added later, as necessary).
         job_data.output_file = os.path.splitext(job_data.output_file)[0]

         # Validate the reference segment and provide a default if not provided.
         job_data.ref_segment = safe_trim(job_data.ref_segment)
         if not job_data.ref_segment:
            job_data.ref_segment = Constants.DEFAULT_REF_SEGMENT

         elif not job_data.ref_segment in Constants.VALID_SEGMENTS:
            raise ValueError(f"Invalid reference segment: {job_data.ref_segment}")

         # Reference tree inference
         if not job_data.ref_tree_inference:
            job_data.ref_tree_inference = TreeInference.FastTree

         # Validate the segments
         segments = safe_trim(job_data.segments)
         if len(segments) > 0:
            for segment in segments.split(","):
               if not segment.upper() in Constants.VALID_SEGMENTS:
                  raise ValueError(f"Invalid segment: {segment}")
         else:
            # TreeSort accepts an empty segments parameter as "all segments", but we are 
            # explicitly populating it here so it can be used when creating the summary file.
            job_data.segments = ",".join(Constants.VALID_SEGMENTS)

      except Exception as e:
         sys.stderr.write(f"Invalid job data:\n {e}\n")
         return False

      return True
   

   # Move intermediate files into a subdirectory in the working directory.
   def move_intermediate_files(self) -> bool:

      sys.stdout.write("\nIn TreeSortRunner.move_intermediate_files\n")

      output_phyloxml_file = f"{self.job_data.output_file}{Constants.PHYLOXML_FILE_EXTENSION}"
      output_tree_file = f"{self.job_data.output_file}{Constants.TREE_FILE_EXTENSION}"

      try:
         output_subdir = f"{self.work_directory}/{Constants.OUTPUT_SUBDIRECTORY_NAME}"
         if not os.path.exists(output_subdir):
            os.mkdir(output_subdir)

         # These files won't be moved to the output subdirectory.
         files_to_exclude = [
            Constants.OUTPUT_SUBDIRECTORY_NAME,
            Constants.SUMMARY_FILENAME, 
            Constants.REASSORTMENTS_FILE_NAME, 
            output_tree_file, 
            output_phyloxml_file
         ]

         # Move "intermediate" (non-final) files and directories to the output subdirectory.
         for item in os.listdir(self.work_directory):
            item_path = os.path.join(self.work_directory, item)
            if item not in files_to_exclude and os.path.exists(item_path):
               subprocess.run(["mv", item_path, output_subdir], shell=False, check=True, capture_output=True)

      except subprocess.CalledProcessError as cpe:  
         sys.stderr.write(f"Error moving intermediate files:\n {cpe.stderr}\n")
         return False
      except Exception as e:
         sys.stderr.write(f"Error moving intermediate files:\n {e}\n")
         return False

      return True


   @staticmethod
   def normalize_collection_date(date_str: Optional[str]) -> str:
      """
      Normalize to YYYY-MM-DD:
         YYYY -> YYYY-01-01
         YYYY-MM -> YYYY-MM-01
         YYYY-MM-DD -> as-is
      Otherwise -> 0000-00-00
      """
      s = safe_trim(date_str)
      if not s:
         return "0000-00-00"
      if re.fullmatch(r"\d{4}-\d{2}-\d{2}", s):
         return s
      if re.fullmatch(r"\d{4}-\d{2}", s):
         return f"{s}-01"
      if re.fullmatch(r"\d{4}", s):
         return f"{s}-01-01"
      return "0000-00-00"

   
   # Parse a line from TreeSort's stdout to look for important info.
   def parse_treesort_stdout_line(self, line: str):

      line = safe_trim(line)

      if not line:
         return
      
      # Skip lines that refer to a tmp directory.
      # TODO: Possibly unnecessary.
      if "/tmp/" in line:
         return
   
      # Look for information not specific to a segment.
      if line.endswith(" strains in common across the alignments.") or \
         line.startswith("Multifurcations resolved: "):

         self.results.treesort_list.append(line)
         return

      # Look for segment-specific reassortment events.
      match = re.search(r'Inferred reassortment events with ([A-Za-z0-9]+):\s*(\d+)', line)
      if match:
         segment_name = safe_trim(match.group(1)).upper()
         event_count = match.group(2)

         # Update the segment data dictionary.
         if segment_name not in self.results.segment_data:
            self.results.segment_data[segment_name] = []

         self.results.segment_data[segment_name].append(f"Inferred reassortment events: {event_count}")

         self.results.current_segment = segment_name

         # TODO: why was I returning from here?
         #return
      
      match = re.search(r"Identified exact branches for (\d+)/\d+ of them", line)
      if match and self.results.current_segment:

         exact_branches = match.group(1)

         current_segment = self.results.current_segment

         if current_segment not in self.results.segment_data:
            self.results.segment_data[current_segment] = []

         self.results.segment_data[current_segment].append(f"Identified exact branches for {exact_branches} of the events")

         # Re-initialize the current segment.
         self.results.current_segment = None

      return
   

   # Parse a line from TreeTime's stdout to look for segment-specific info.
   def parse_treetime_stdout_line(self, line: str, segment_name: str):

      # Root-Tip-Regression info
      
      # Rate
      match = re.search(r"\S*--rate:\s*(\S+)", line)
      if match:
         rate = match.group(1)

         if not segment_name in self.results.segment_data:
            self.results.segment_data[segment_name] = []

         self.results.segment_data[segment_name].append(f"Estimated substitution rate: {rate}")
         return
      
      # R^2
      match = re.search(r'\S*\-\-r\^2:\s*(\d+\.\d+)', line)
      if match:
         r_2 = match.group(1)

         if not segment_name in self.results.segment_data:
            self.results.segment_data[segment_name] = []

         self.results.segment_data[segment_name].append(f"Fraction of variation in root-to-tip distance: {r_2}")
         return
      
      r"""
      TODO: Make sure this works correctly and then re-add it.
      
      # Root date
      #match = re.search(r"\S*---\s*root-date:\s*(\d+\.\d+)", line)
      if match:
         decimal_date = match.group(1)

         root_date = "invalid"

         # Convert the floating point date to a standard format.
         date_match = re.search(r'(\d+).(\d+)', decimal_date)
         if date_match:

            year = date_match.group(1)
            decimal_part = date_match.group(2)

            # Convert the root date formatted as a decimal to a standard MM/DD/YYYY.
            root_date = self.format_root_date(decimal_part, year)

            if not segment_name in self.results.segment_data:
               self.results.segment_data[segment_name] = []

            self.results.segment_data[segment_name].append(f"The root date is {root_date}")
            return
      """

      return
   

   """def filter_ids_by_segments(self, genome_ids: List[str], meta: Dict[str, Dict[str, str]]) -> List[str]:
      ""
      Keep only genomes whose metadata.segment(s) are in requested_segments.
      ""
      if requested_segments is None or len(requested_segments) < 1:
         # If empty means "all segments" in TreeSort, then don't filter.
         return genome_ids

      # TEST
      sys.stdout.write(f"requested_segments = {str(requested_segments)}\n")

      kept: List[str] = []

      for gid in genome_ids:
         m = meta.get(gid)
         if not m:
            continue

         segments = safe_trim(m.get("segment"))
         if segments is None:
            continue

         # Remove whitespace and convert to uppercase.
         segments = segments.replace(" ", "").upper()

         sys.stdout.write(f"genome segments: {segments}\n")

         segment_list = segments.split(",")
         if not set(segment_list).issubset(set(requested_segments)):
            # TODO: We could gracefully handle this by filtering the genome's FASTA later on.
            continue

         kept.append(gid)

      return kept"""


   # Determine the source of the FASTA input file and prepare it for use.
   def prepare_input_file(self) -> bool:

      sys.stdout.write("\nIn TreeSortRunner.prepare_input_file\n")

      try:
         # The input source determines how the input file is provided.
         input_source = safe_trim(self.job_data.input_source)

         if input_source == InputSource.FastaFileID.value:

            # Populate the input filename, including its full path.
            self.input_filename = f"{self.input_directory}/{Constants.INPUT_FASTA_FILE_NAME}"

            try:
               # Copy the input file from the workspace to the working directory.
               fetch_fasta_cmd = ["p3-cp", f"ws:{self.job_data.input_fasta_file_id}", self.input_filename]
               subprocess.run(fetch_fasta_cmd, shell=False, capture_output=True, check=True)

            except subprocess.CalledProcessError as cpe:  
               sys.stderr.write(f"Error copying FASTA from workspace:\n {cpe.stderr}\n")
               return False
            except Exception as e:
               raise IOError("Error copying FASTA file from workspace:\n %s" % str(e))

         elif input_source == InputSource.FastaGroupID.value:

            # Create the input filename
            self.input_filename = f"{self.input_directory}/{Constants.INPUT_FASTA_FILE_NAME}"

            group_path = safe_trim(self.job_data.input_fasta_group_id)
            if len(group_path) < 1:
               raise ValueError("Invalid input genome group id/path")

            # Build input.fasta from the genome group (downloads genome FASTA + rewrites headers)
            if not self.build_input_fasta_from_group(group_path, self.input_filename):
               raise Exception("Unable to build input FASTA from genome group")

         elif input_source == InputSource.FastaExistingDataset.value:

            # TODO: Figure out the best way to handle this scenario.
            raise ValueError("Processing an existing dataset is not yet implemented")

         elif input_source == InputSource.FastaData.value:
      
            # Create the input filename, including its full path.
            self.input_filename = f"{self.input_directory}/{Constants.INPUT_FASTA_FILE_NAME}"

            try:
               # Create a file that contains the input FASTA data.
               with open(self.input_filename, "w+") as input_file:
                  input_file.write(str(self.job_data.input_fasta_data))

            except Exception as e:
               raise IOError(f"Error copying FASTA data to input file:\n {e}\n")

         else:
            raise ValueError(f"Invalid input source: {input_source}")

         # Validate the input filename.
         if not self.input_filename:
            raise ValueError("Invalid input filename (empty)")
         
         # Validate the input FASTA file.
         if not os.path.exists(self.input_filename) or os.path.getsize(self.input_filename) == 0:
            raise IOError("Input FASTA file is invalid or empty")
  
         # TODO: This is a good place to validate the input FASTA file. Currently, the 
         # FASTA header requires the segment name/abbreviation surrounded by |'s and a date at the end.

      except subprocess.CalledProcessError as cpe:  
         sys.stderr.write(f"Error processing input file:\n {cpe.stderr}\n")
         return False
      except Exception as e:
         sys.stderr.write(f"Error processing input file:\n {e}\n")
         return False
      
      return True


   def process_genome_fasta(self, fasta_text: str, genome: GenomeMetadata) -> str:
      """
      Iterate over every sequence, reformatting header lines as ">STRAIN|SUBTYPE|SEGMENT|YYYY-MM-DD", only
      include sequences for requested segments, and make sure a sequence for the reference segment exists.
      """

      found_segments: list[str] = []

      segment_name = None
      skip_sequence = False

      output_fasta = []

      for line in fasta_text.splitlines(keepends=True):

         # Is this is a header line?
         if line.startswith(">"):

            # Example FASTA header in the input: "">1173138.25.con.0006 segment"
            match = re.search(r'\.([^.\s]+)\s+segment', line)
            if not match:
               sys.stderr.write(f"Invalid FASTA header format for genome {genome.genome_id}: {line}")
               skip_sequence = True
               continue
            
            # Get the segment number from the header
            segment_num_str = match.group(1)

            # Convert to an int to get rid of zero-padding on the left side.
            segment_num = int(segment_num_str)

            # Convert numeric segment to canonical name
            segment_name = Constants.SEGMENT_NUM_TO_NAME.get(str(segment_num)) or ""

            if segment_name not in self.segments:
               sys.stderr.write(f"Skipping the sequence for segment {segment_name} in genome {genome.genome_id}")
               skip_sequence = True
               continue

            if segment_name in found_segments:
               sys.stderr.write(f"Duplicate sequence found for segment {segment_name} in genome {genome.genome_id}")
               skip_sequence = True
               continue

            found_segments.append(segment_name)

            # Don't skip the following lines of bases.
            skip_sequence = False
            
            # Replace the FASTA header
            strain = genome.strain.replace(" ", "_")
            output_fasta.append(f">{strain}|{genome.subtype}|{segment_name}|{genome.collection_date}\n")

         elif not skip_sequence:
            # Sequence data
            output_fasta.append(line)

      # Did we find enough segments?
      if len(found_segments) < 2:
         sys.stderr.write(f"Excluding FASTA for genome {genome.genome_id}: Not enough segments for analysis ({len(found_segments)})")
         return ""

      # Did we find the reference segment?
      if self.job_data.ref_segment not in found_segments:
         sys.stderr.write(f"Excluding FASTA for genome {genome.genome_id}: No sequence found for reference segment ({self.job_data.ref_segment})")
         return ""

      return "".join(output_fasta)
   

   def process_phyloxml_clade(self, m: re.Match):

      # empty_clade = "<clade>"

      clade: str | None = m.group("clade")
      if not clade:
         return "<clade>"
      
      branch = ""
      is_reassorted = False
      is_tsnode = False
      is_uncertain = False
      name = ""
      properties = []
      property = ""
      ts_node_name = ""

      # All reassorted segment inferences found in the clade XML.
      segments = []

      # A comma-delimited list of segment(distance).
      segments_label = ""

      # Get the name element
      name_match = PHYLOXML_REGEX.NAME.search(clade)
      if not name_match:
         sys.stderr.write(f"Error in process_phyloxml_clade: No name match for {clade}\n")
         return clade
      
      name = name_match.group("name")
      if not name:
         sys.stderr.write(f"Error in process_phyloxml_clade: Name is empty\n")
         return clade

      name = name.strip()

      # Is this a TS_NODE_* node?
      if name.startswith("TS_NODE_"):
         is_tsnode = True

         # Populate the TS_node name
         ts_node_name = str(name)

         # Clear the name
         name = ""

      # Get the branch length
      branch_match = PHYLOXML_REGEX.BRANCH_LIST.search(clade)
      if not branch_match:
         branch = ""
      else:
         branch = branch_match.group("branch")
         if not branch:
            branch = ""

      # Look for a comment property
      property_match = PHYLOXML_REGEX.PROPERTY.search(clade)
      if property_match:
         property = property_match.group("value")
         if property and len(property) > 0:

            # Does the comment property contain "is_reassorted=1"?
            reassorted_match = PHYLOXML_REGEX.REASSORTED.search(property)
            if reassorted_match and reassorted_match.group("reassorted") == "1":
               is_reassorted = True
            
               # Iterate over every segment(distance) expression.
               for sd in PHYLOXML_REGEX.SEGMENT_AND_DIST.finditer(property):
                  segment, distance = sd.group("segment"), sd.group("distance")
                  if not segment:
                     continue

                  if len(segments) > 0:
                     segments_label += ", "

                  segments_label += f"{segment}({distance})"

                  if segment.startswith("?"):
                     is_uncertain = True

                  segments.append(segment)

      if is_reassorted and len(segments) > 0:
         if is_tsnode:
            # The TS_* node name is replaced by segment(distance) value(s).
            name = segments_label

            segment_list = ",".join(segments)

            # Add an empty segment property.
            properties.append(f"<property ref=\"{PHYLOXML_PROPERTY_REF.segment}\" datatype=\"xsd:string\" applies_to=\"node\">{segment_list}</property>")
         
         elif len(name) > 0:
            # Preface the name with the segments label.
            name = f"{segments_label}: {name}"

            # Add a property for every segment.
            for segment in segments:
               properties.append(f"<property ref=\"{PHYLOXML_PROPERTY_REF.segment}\" datatype=\"xsd:string\" applies_to=\"node\">{segment}</property>")
      else:
         # Add an empty segment property
         properties.append(f"<property ref=\"{PHYLOXML_PROPERTY_REF.segment}\" datatype=\"xsd:string\" applies_to=\"node\"></property>")

      # Add properties for "is_reassorted", "is_uncertain", and "node_id".
      properties.append(f"<property ref=\"{PHYLOXML_PROPERTY_REF.isReassorted}\" datatype=\"xsd:string\" applies_to=\"node\">{"yes" if is_reassorted else "no"}</property>")
      properties.append(f"<property ref=\"{PHYLOXML_PROPERTY_REF.isUncertain}\" datatype=\"xsd:string\" applies_to=\"node\">{"yes" if is_uncertain else "no"}</property>")
      properties.append(f"<property ref=\"{PHYLOXML_PROPERTY_REF.nodeID}\" datatype=\"xsd:string\" applies_to=\"node\">{ts_node_name}</property>")

      property_elements = "".join(properties)

      return (
         "<clade>"
         f"<name>{name}</name>"
         f"<branch_length>{branch}</branch_length>"
         f"{property_elements}"
      )


   # Parse the segment-specific output files containing TreeTime's stdout.
   def process_treetime_stdout_files(self):

      segments = safe_trim(self.job_data.segments)
      if len(segments) < 1:
         sys.stderr.write("No segments were found in process_treetime_stdout_files")
         return

      # Iterate over all segments
      for segment in segments.split(","):

         segment = safe_trim(segment)

         output_filename = f"{self.work_directory}/{segment}{Constants.TREETIME_STDOUT_FILE_SUFFIX}"
   
         try:
            # Open the segment-specific output file.
            with open(output_filename, "r", encoding="utf-8") as output_file:

               lines = output_file.readlines()

               # The first line should contain the segment name.
               segment_name = safe_trim(lines[0])
               if segment_name.startswith("SEGMENT: "):
                  segment_name = segment_name.replace("SEGMENT: ", "")

               # Iterate over every line after the first line.
               for line in lines[1:]:

                  # Parse a line from TreeTime-root's stdout.
                  self.parse_treetime_stdout_line(line, segment_name)

         except FileNotFoundError:
            continue

      return
   

   # Run prepare_dataset.sh to build alignments and trees and compile a descriptor file.
   def run_prepare_dataset(self) -> bool:

      sys.stdout.write("\nIn TreeSortRunner.run_prepare_dataset\n")
      
      # The result status defaults to false.
      result_status = False

      try:
         cmd = ["prepare_treesort_dataset"]

         # Specify the reference tree inference method.
         # TODO: Consider supporting RAxML in addition to FastTree and IQ-Tree. 
         if (self.job_data.ref_tree_inference and self.job_data.ref_tree_inference == TreeInference.FastTree.value):
            cmd.append(ScriptOption.FastTree.value)

         # The segments (optional)
         if self.job_data.segments:
            cmd.append(ScriptOption.Segments.value)
            cmd.append(self.job_data.segments)

         # The input FASTA file
         cmd.append(self.input_filename)

         # The reference segment
         refSegment = self.job_data.ref_segment
         if refSegment:
            cmd.append(refSegment)

         # The working directory
         cmd.append(self.work_directory)

         # Display the command about to be run.
         print(f"{' '.join(cmd)}\n")

         result = subprocess.run(cmd, shell=False, capture_output=True, text=True, check=True)
         if result.returncode == 0:
            
            result_status = True

            # Iterate over lines in the result's stdout to 1) look for the segments 
            # that were found, 2) parse TreeTime data by segment, and 3) to echo messages 
            # to stdout.
            for line in result.stdout.strip().splitlines():

               if line.startswith("FOUND_SEGMENTS:"):
                  self.job_data.segments = line.replace("FOUND_SEGMENTS:", "").strip()

                  print(f"job_data.segments has been updated to {self.job_data.segments}")

               else:
                  # Write the script's stdout to run_treesort.py's stdout.
                  sys.stdout.write(f"{line}\n")

      except subprocess.CalledProcessError as cpe:  
         sys.stderr.write(f"Error preparing dataset:\n {cpe.stderr}\n")
         return False
      except Exception as e:
         sys.stderr.write(f"Error preparing dataset:\n {e}\n")
         return False
         
      return result_status


   # Run TreeSort in a sub-process.
   def tree_sort(self) -> bool:

      sys.stdout.write("\nIn TreeSortRunner.tree_sort\n")
      
      # The result status defaults to false.
      result_status = False

      try:
         cmd = ["treesort"]

         # The clades output path
         clades_path = safe_trim(self.job_data.clades_path)
         if len(clades_path) > 0:
            cmd.append(ScriptOption.CladesPath.value)
            cmd.append(clades_path)

         # The descriptor file is in the working directory.
         cmd.append(ScriptOption.DescriptorPath.value)
         cmd.append(f"{self.work_directory}/{Constants.DESCRIPTOR_FILE_NAME}")

         #-----------------------------------------------------------------------------------------------------------------------------
         # The "match on" options are mutually exclusive.
         #-----------------------------------------------------------------------------------------------------------------------------
         if self.job_data.match_type == MatchType.Strain:
            cmd.append(ScriptOption.MatchOnStrain.value)

         elif self.job_data.match_type == MatchType.EPI:
            cmd.append(ScriptOption.MatchOnEPI.value)

         elif self.job_data.match_type == MatchType.RegEx and self.job_data.match_regex:
            cmd.append(ScriptOption.MatchOnRegex.value)
            cmd.append(self.job_data.match_regex)

         # No collapse
         if self.job_data.no_collapse:
            cmd.append(ScriptOption.NoCollapse.value)

         # The name of the output file to create in the work directory. 
         cmd.append(ScriptOption.OutputFilename.value)
         cmd.append(f"{self.work_directory}/{self.job_data.output_file}{Constants.TREE_FILE_EXTENSION}")
         
         # Equal rates
         if self.job_data.equal_rates:
            cmd.append(ScriptOption.EqualRates.value)

         # Deviation
         cmd.append(ScriptOption.Deviation)
         cmd.append(str(self.job_data.deviation))

         # Inference method
         if self.job_data.inference_method:
            cmd.append(ScriptOption.InferenceMethod.value)
            cmd.append(InferenceMethod(self.job_data.inference_method).value) # NOTE: this seems overly-complex

         # P-value
         cmd.append(ScriptOption.PValue)
         cmd.append(str(self.job_data.p_value))

         # Print the treesort command line that will be run.
         print(f"{' '.join(cmd)}\n")

         # Run the command
         result = subprocess.run(cmd, capture_output=True, text=True, check=True)

         # Update the results object with TreeSort's stdout.
         self.results.treesort_stdout = result.stdout

         if result.returncode == 0:
            result_status = True

      except subprocess.CalledProcessError as cpe:  
         sys.stderr.write(f"Error in TreeSort:\n {cpe.stderr}\n")
         return False       
      except Exception as e:
         sys.stderr.write(f"Error in TreeSort:\n {type(e).__name__}: {e}\n")
         return False
      
      return result_status


   # Validate the job's input_source.
   @staticmethod
   def validate_input_source(job_data: JobData) -> bool:

      if job_data.input_source not in [i.value for i in InputSource]:
         raise ValueError("job_data.input_source is not a valid input source") 

      if job_data.input_source == InputSource.FastaFileID.value:

         # Make sure an input_fasta_file_id value was provided.
         if not job_data.input_fasta_file_id:
            raise ValueError("The input FASTA file ID is invalid")
         
         elif job_data.input_fasta_file_id.startswith("ws:"):

            # Remove the "ws:" prefix from the directory name.
            job_data.input_fasta_file_id = job_data.input_fasta_file_id[3:]

      elif job_data.input_source == InputSource.FastaGroupID.value:

         # Make sure an input_fasta_group_id value was provided.
         if not job_data.input_fasta_group_id:
            raise ValueError("The input FASTA group ID is invalid")

      elif job_data.input_source == InputSource.FastaData:

         if job_data.input_fasta_data is None or len(job_data.input_fasta_data) < 1:
            raise ValueError("The input FASTA data is invalid")
         
      else:
         raise ValueError("The input source is invalid")
      
      return True
   

def main(argv=None) -> bool:
    
   # Exclude the script name.
   if argv is None:
      argv = sys.argv[1:]  

   # Create an argument parser.
   parser = argparse.ArgumentParser(description="A script to run TreeSort")
   parser.add_argument("-i", "--input-directory", dest="input_directory", help="The directory with FASTA input file(s)", required=True)
   parser.add_argument("-j", "--job-filename", dest="job_filename", help="The job description JSON file", required=True)
   parser.add_argument("-w", "--work-directory", dest="work_directory", help="The directory where intermediate files are generated", required=True)
   
   args = parser.parse_args()

   # The input directory parameter.
   input_directory = safe_trim(args.input_directory)
   if len(input_directory) == 0:
      traceback.print_exc(file=sys.stderr)
      sys.stderr.write("Invalid input directory parameter\n")
      return False

   # The job filename parameter.
   job_filename = safe_trim(args.job_filename)
   if len(job_filename) == 0:
      traceback.print_exc(file=sys.stderr)
      sys.stderr.write("Invalid job filename parameter\n")
      return False

   # The work directory parameter.
   work_directory = safe_trim(args.work_directory)
   if len(work_directory) == 0:
      traceback.print_exc(file=sys.stderr)
      sys.stderr.write("Invalid work directory parameter\n")
      return False

   job_data = None

   try:
      # Load job data from the JSON file.
      with open(job_filename, "r", encoding="utf-8") as job_file:
         job_dict = json.load(job_file)
         job_data = JobData(**job_dict)

   except Exception as e:
      traceback.print_exc(file=sys.stderr)
      sys.stderr.write(f"Invalid job file:\n{e}\n")
      return False

   try:
      # Create a TreeSortRunner instance
      runner = TreeSortRunner(input_directory, job_data, work_directory)

   except Exception as e:
      traceback.print_exc(file=sys.stderr)
      sys.stderr.write(f"Unable to create an instance of TreeSortRunner:\n{e}\n")
      return False
   
   # Prepare the input file
   if not runner.prepare_input_file():
      traceback.print_exc(file=sys.stderr)
      sys.stderr.write("An error occurred in TreeSortRunner.prepare_input_file\n")
      return False

   # The start time of prepare_dataset.
   pd_start = datetime.now()

   # Prepare the dataset
   if not runner.run_prepare_dataset():
      traceback.print_exc(file=sys.stderr)
      sys.stderr.write("An error occurred in TreeSortRunner.run_prepare_dataset\n")
      return False

   # Print the end time and total duration of prepare_dataset.
   print(f"Finished prepare_dataset at {TreeSortRunner.format_end_datetime_with_duration(datetime.now(), pd_start)}")

   # Run TreeSort
   if not runner.tree_sort():
      traceback.print_exc(file=sys.stderr)
      sys.stderr.write("An error occurred in TreeSortRunner.tree_sort\n")
      return False
   
   # Parse the annotated tree file for reassorted strains and create "reassortments.csv".
   if not runner.create_reassortments_csv_file():
      sys.stderr.write("An error occurred creating the reassortments CSV file")
      return False

   # Create a PhyloXML version of the result tree.
   if not runner.export_tree_as_phyloxml():
      sys.stderr.write("An error occurred creating the PhyloXML file")
      return False
   
   # Create a summary HTML file.
   if not runner.create_summary_html():
      traceback.print_exc(file=sys.stderr)
      sys.stderr.write("An error occurred in TreeSortRunner.create_summary_html\n")
      return False

   # Delete intermediate files that are not needed in the output.
   if not runner.delete_unnecessary_files():
      sys.stderr.write("An error occurred deleting unnecessary files\n")

   # Move intermediate files into a subdirectory in the working directory.
   if not runner.move_intermediate_files():
      sys.stderr.write("An error occured moving intermediate files\n")

   return True


if __name__ == "__main__" :

   # Print the start time to stdout.
   start_time = datetime.now()
   sys.stdout.write(f"Started at {TreeSortRunner.format_datetime(start_time)}")
      
   result = main()

   # Print the end time and total duration of main.
   sys.stdout.write(f"Finished at {TreeSortRunner.format_end_datetime_with_duration(datetime.now(), start_time)}")

   if result:
      sys.exit(0)
   else:
      sys.exit(1)
   
